name: Scrape TimeTree and Update Google Calendar

on:
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ステップ 2: Python環境をセットアップ
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # ステップ 3: pipのキャッシュパスを取得
      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT

      # ステップ 4: pipのキャッシュを有効化
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # ステップ 5: 依存ライブラリをインストール
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # ステップ 6: Playwrightのキャッシュパスを取得
      - name: Get Playwright cache dir
        id: playwright-cache
        run: |
          echo "dir=$(npx playwright print-driver-path | xargs -n 1 dirname)" >> $GITHUB_OUTPUT
      
      # ステップ 7: Playwrightのブラウザをキャッシュ
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ${{ steps.playwright-cache.outputs.dir }}
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      # ステップ 8: PlaywrightのブラウザとOS依存関係をインストール
      - name: Install Playwright and dependencies
        run: playwright install --with-deps

      # ステップ 9: Pythonスクリプトを実行
      - name: Run scraper script
        env:
          TIMETREE_EMAIL: ${{ secrets.TIMETREE_EMAIL }}
          TIMETREE_PASSWORD: ${{ secrets.TIMETREE_PASSWORD }}
          TIMETREE_CALENDAR_URL: ${{ secrets.TIMETREE_CALENDAR_URL }}
          GAS_WEBAPP_URL: ${{ secrets.GAS_WEBAPP_URL }}
        run: python timetree_scraper.py