
# GitHub Actionsワークフローファイル
# ファイル名: .github/workflows/main.yml

name: Scrape TimeTree and Update Google Calendar

on:
  # 毎日午前0時 (UTC) に自動実行
  # 日本時間の午前9時に相当します。時間は自由に変更してください。
  # 例: 日本時間の午前7時にしたい場合 -> cron: "0 22 * * *"
  schedule:
    - cron: "0 */1 * * *"
  
  # GitHubのActionsタブから手動で実行することも可能にする
  workflow_dispatch:

jobs:
  scrape-and-update:
    # 実行環境として最新のUbuntuを使用
    runs-on: ubuntu-latest

    env:
      TZ: Asia/Tokyo

    steps:
      # 1. リポジトリのコードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 依存関係をインストール（キャッシュ有効化）
      - name: Setup Python, Dependencies and Playwright
        uses: microsoft/playwright-python-action@v1
        with:
          # requirements.txt を使って依存関係をインストールするように指示
          install-deps-from: 'requirements.txt'

      # 3. Pythonスクリプトを実行
      # GitHub Secretsから認証情報を環境変数としてスクリプトに渡す
      - name: Run scraper script
        env:
          TIMETREE_EMAIL: ${{ secrets.TIMETREE_EMAIL }}
          TIMETREE_PASSWORD: ${{ secrets.TIMETREE_PASSWORD }}
          TIMETREE_CALENDAR_URL: ${{ secrets.TIMETREE_CALENDAR_URL }}
          GAS_WEBAPP_URL: ${{ secrets.GAS_WEBAPP_URL }}
        run: python timetree_scraper.py

